Swapnali
cristian-castro-a/global-avg-temperature-forecasting pull request #23
Opened 2023-01-20 21:38 UTC by swapnalisonkusale

preprocessed the dataset of energy substitution, world population and world employment.

2023-01-20 21:44 UTC, Tejas-Choudekar approved these changes

2023-01-21 08:09 UTC, cristian-castro-a requested changes

2023-01-21 08:09 UTC, cristian-castro-a commented on exploratory_data_analysis/eda.py
> +from utils.plotting import plot_lines_by
Please do not include this import as we are not using it. Pull from main to get the last version.

2023-01-21 08:09 UTC, cristian-castro-a commented on utils/preprocessing.py
> +    df['global_energy_substitution'] = df[column_list].sum(axis=1)
A more efficient way with way fewer lines of code would be: df.filter(like='substituted energy', axis=1)

2023-01-21 08:09 UTC, cristian-castro-a commented on utils/preprocessing.py
> +    df = df[df['date'].dt.year > 1964]
Why we are taking only the years > 1964? Please add a comment.

2023-01-21 10:26 UTC, cristian-castro-a approved these changes

2023-01-21 21:31 UTC, Tejas-Choudekar approved these changes

2023-01-21 21:33 UTC, merged